# Lint Rules
opt_in_rules:
#    - anyobject_protocol
    - attributes
    - array_init
    - balanced_xctest_lifecycle
    - blanket_disable_command
    - block_based_kvo
    - closing_brace
    - closure_parameter_position
    - collection_alignment
    - colon
    - comma
    - comma_inheritance
    - comment_spacing
    - compiler_protocol_init
    - computed_accessors_order
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - convenience_type
    - control_statement
    - direct_return
    - discarded_notification_center_observer
    - discouraged_assert
    - discouraged_direct_init
    - duplicate_conditions
    - duplicate_enum_cases
    - duplicate_imports
    - duplicated_key_in_dictionary_literal
    - empty_count
    - empty_enum_arguments
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - empty_string
    - empty_xctest_method
    - explicit_acl
    - explicit_top_level_acl
    - fatal_error_message
    - first_where
    - flatmap_over_map_reduce
    - for_where
    - force_cast
    - force_try
    - force_unwrapping
    - generic_type_name
    - identical_operands
    - identifier_name
    - implicit_getter
    - implicit_return
    - implicitly_unwrapped_optional
    - invalid_swiftlint_command
    - is_disjoint
    - joined_default_parameter
    - large_tuple
    - last_where
    - leading_whitespace
    - legacy_cggeometry_functions
    - legacy_constant
    - legacy_constructor
    - legacy_hashing
    - legacy_nsgeometry_functions
    - legacy_objc_type
    - legacy_random
    - line_length
    - local_doc_comment
    - lower_acl_than_parent
    - mark
    - missing_docs
    - modifier_order
    - multiline_arguments
    - multiline_arguments_brackets
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - no_extension_access_modifier
    - no_fallthrough_only
    - no_space_in_method_call
    - ns_number_init_as_function_reference
    - nsobject_prefer_isequal
    - opening_brace
    - operator_whitespace
    - orphaned_doc_comment
    - private_unit_test
    - protocol_property_accessors_order
    - reduce_boolean
    - redundant_discardable_let
    - redundant_objc_attribute
    - redundant_optional_initialization
    - redundant_set_access_control
    - redundant_string_enum_value
    - redundant_void_return
    - return_arrow_whitespace
    - self_in_property_initialization
    - shorthand_operator
    - superfluous_disable_command
    - switch_case_alignment
    - syntactic_sugar
    - trailing_comma
    - trailing_newline
    - trailing_semicolon
    - trailing_whitespace
    - type_name
    - unavailable_condition
    - unneeded_break_in_switch
    - unused_closure_parameter
    - unused_control_flow_label
    - unused_enumerated
    - unused_optional_binding
    - unused_setter_value
    
disabled_rules:
    - accessibility_label_for_image
    - accessibility_trait_for_button
    - anonymous_argument_in_multiline_closure
    - class_delegate_protocol
    - closure_body_length
    - conditional_returns_on_newline
    - custom_rules
    - cyclomatic_complexity
    - deployment_target
    - discouraged_none_name
    - discouraged_object_literal
    - discouraged_optional_boolean
    - discouraged_optional_collection
    - enum_case_associated_values_count
    - expiring_todo
    - explicit_enum_raw_value
    - explicit_init
    - explicit_type_interface
    - extension_access_modifier
    - fallthrough
    - file_header
    - file_length
    - file_name
    - file_name_no_space
    - file_types_order
    - function_body_length
    - function_default_parameter_at_end
    - function_parameter_count
    - ibinspectable_in_extension
    - inclusive_language
    - indentation_width
    - legacy_multiple
    - let_var_whitespace
    - literal_expression_end_indentation
    - multiple_closures_with_trailing_closure
    - nesting
    - nimble_operator
    - notification_center_detachment
    - private_over_fileprivate
    - statement_position
    - todo
    - type_body_length
    - valid_ibinspectable
    - vertical_parameter_alignment
    - vertical_whitespace
    - void_function_in_ternary
    - void_return
    - xctfail_message

# Paths to ignore.
excluded:
    - Carthage
    - Pods
# Paths to include.
included:
    - Sources
    - Tests

# SwiftLint fails if no lintable files are found.
allow_zero_lintable_files: false

# Rule Configuration
force_cast: warning
force_try: warning
identifier_name:
    min_length: 3
    error: 4
    excluded:
    - pi
    - x
    - y
    - dx
    - dy
    - fn
    - id
    - URL
    allowed_symbols: ["_"]
large_tuple:
    warning: 4
    error: 6
line_length:
    warning: 120
    error: 200
type_name:
    allowed_symbols: ["_"]
missing_docs:
    excludes_extensions: false
    excludes_inherited_types: false
reporter: "xcode"

